### ISSUE TITLE
can it be triggered by a hotkey?

### ISSUE THREAD

**Issue by hiccup2** [SlashScreen/rate-your-genres#1]
Hi SlashScreen

Thanks for creating and sharing this!
A question, could it be made so that the search for genres can be triggered using a hotkey?
And/or a toolbar button?

Cheers!

**Comment by SlashScreen** [comment]
oh, go to `tools>Search genres for selected music` to trigger it.

**Comment by hiccup2** [comment]
Yes, I know that. But my question is if it would be possible to trigger it using a hotkey.
That would be much easier and faster than navigating through the menu with the mouse.

**Comment by SlashScreen** [comment]
maybe, but if I am honest I'm about done developing this, and will only touch it if it causes it to crash or something, sorry. I don't want to fiddle with the poorly-documented musicbee API again. If you really want to see a change, I am open to PRs.
